import { addDoc, collection } from "firebase/firestore";
import db from "../db/db.js";

const productos = [
    {
      id: "ccr-01",
      titulo: "Creedence Clearwater Revival",
      imagen: "/img/ccr/01.jpg",
      banda: "Creedence Clearwater Revival",
      categoria: "creedence",
      precio: 1000,
      stock: 100,
    },
    {
      id: "ccr-02",
      titulo: "Bayou Country",
      imagen: "/img/ccr/02.jpg",
      banda: "Creedence Clearwater Revival",
      categoria: "creedence",
      precio: 1000,
      stock: 100,
    },
    {
      id: "ccr-03",
      titulo: "Pendulum",
      imagen: "/img/ccr/03.jpg",
      banda: "Creedence Clearwater Revival",
      categoria: "creedence",
      precio: 1000,
      stock: 100,
    },
    {
      id: "ccr-04",
      titulo: "Green River",
      imagen: "/img/ccr/04.jpg",
      banda: "Creedence Clearwater Revival",
      categoria: "creedence",
      precio: 1000,
      stock: 100,
    },
    {
      id: "ccr-05",
      titulo: "Cosmo's Factory",
      imagen: "/img/ccr/05.jpg",
      banda: "Creedence Clearwater Revival",
      categoria: "creedence",
      precio: 1000,
      stock: 100,
    },
    {
      id: "ccr-06",
      titulo: "Willy and The Poor Boys",
      imagen: "/img/ccr/06.jpg",
      banda: "Creedence Clearwater Revival",
      categoria: "creedence",
      precio: 1000,
      stock: 100,
    },
    {
      id: "ccr-07",
      titulo: "Mardi Gras",
      imagen: "/img/ccr/07.jpg",
      banda: "Creedence Clearwater Revival",
      categoria: "creedence",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-01",
      titulo: "The Rolling Stones",
      imagen: "/img/trs/1.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-02",
      titulo: "12 x 5",
      imagen: "/img/trs/2.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-03",
      titulo: "The Rolling Stones No.2",
      imagen: "/img/trs/3.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-04",
      titulo: "The Rolling Stones, Now! ",
      imagen: "/img/trs/4.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-05",
      titulo: "Out of Our Heads",
      imagen: "/img/trs/5.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-06",
      titulo: "December's Children (And Everybody's) ",
      imagen: "/img/trs/6.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-07",
      titulo: "Aftermath",
      imagen: "/img/trs/7.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-08",
      titulo: "Between the Buttons",
      imagen: "/img/trs/8.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-09",
      titulo: "Flowers",
      imagen: "/img/trs/9.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-10",
      titulo: "Their Satanic Majesties Request",
      imagen: "/img/trs/10.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-11",
      titulo: "Beggars Banquet",
      imagen: "/img/trs/11.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-12",
      titulo: "Let It Bleed",
      imagen: "/img/trs/12.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-13",
      titulo: "Sticky Fingers",
      imagen: "/img/trs/13.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-14",
      titulo: "Exile on Main St.",
      imagen: "/img/trs/14.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-15",
      titulo: "Goats Head Soup",
      imagen: "/img/trs/15.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-16",
      titulo: "It's Only Rock'n'Roll",
      imagen: "/img/trs/16.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-17",
      titulo: "Black and Blue",
      imagen: "/img/trs/17.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-18",
      titulo: "Some Girls",
      imagen: "/img/trs/18.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-19",
      titulo: "Emotional Rescue",
      imagen: "/img/trs/19.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-20",
      titulo: "Tattoo You",
      imagen: "/img/trs/20.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-21",
      titulo: "Undercover",
      imagen: "/img/trs/21.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-22",
      titulo: "Dirty Work",
      imagen: "/img/trs/22.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-23",
      titulo: "Steel Wheels",
      imagen: "/img/trs/23.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-24",
      titulo: "Voodoo Lounge",
      imagen: "/img/trs/24.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
    {
      id: "therollingstones-25",
      titulo: "Bridges to Babylon",
      imagen: "/img/trs/25.jpg",
      banda: "The Rolling Stones",
      categoria: "therollingstones",
      precio: 1000,
      stock: 100,
    },
  ];
  

    const seedProducts = () => {
        productos.map( ( {id, ...rest } ) =>{
            const productosRef = collection(db, "productos")
            addDoc(productosRef, rest)
        } )

        console.log("Productos subidos")
    }


    seedProducts()

